language: objective-c
osx_image: xcode10.2
cache:
  directories:
  - XCFit-Demo/Carthage

before_install:
  - gem install fastlane

install: true
script:
  - cd XCFit-Demo
  - carthage bootstrap --platform iOS
  - fastlane scan -s XCFit-Demo
